name: Run Python script

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: Run script
      run: python workout_progress.py

    - name: Upload workout progress image
      uses: actions/upload-artifact@v2
      with:
        name: workout-progress-image
        path: workout_progress.png
